"""Initial migration

Revision ID: 68f033097fe5
Revises: 833071ff634c
Create Date: 2024-11-26 17:34:52.532318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f033097fe5'
down_revision: Union[str, None] = '833071ff634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('food_item_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_items_food_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'food_items', ['food_item_id'], ['id'])
    op.drop_column('order_items', 'food_id')
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=True))
    op.drop_constraint('orders_food_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'food_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_food_id_fkey', 'orders', 'food_items', ['food_id'], ['id'])
    op.drop_column('orders', 'total_price')
    op.add_column('order_items', sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_food_id_fkey', 'order_items', 'food_items', ['food_id'], ['id'])
    op.drop_column('order_items', 'food_item_id')
    # ### end Alembic commands ###
