"""orders

Revision ID: c91c105e3976
Revises: dfb2e96fd5fd
Create Date: 2024-11-26 17:52:27.774000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91c105e3976'
down_revision: Union[str, None] = 'dfb2e96fd5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
